### PR TITLE
Battle 2k: Fix bugs when selecting a previous actor.

### LINKED ISSUE #933: RPG2k battle: Some actors (randomly) get two actions in a turn assigned
**Name of the game**: Vampires Dawn (probably all RPG 2k games with battles)

**Player platform** (e.g. Windows, Linux, Android, ...): Android (or Any?)

EDIT: The reason seems to be that an actor gets two action per turn, which results in the 2nd action being deleted when the first action finished -> nullptr crash. This is now circumvented by adding a check for this and issuing a warning to the user. How it happens is not clear yet, at least "cancel" to select a previous actor clears the actions correctly.

Vampires Dawn crashes randomly in battles.
According to the stack trace (I finally have line numbers \o/) the crash is last calls are:

```
battle_actions.front()->GetBattleAlgorithm().get())
action->IsFirstAttack()
Crash in IsFirstAttack
```

This obviously means that action is an invalid pointer. More likely is a nullptr, I see no reason how this can happen. Will add more debug output for this corner case.

```
********** Crash dump: **********
Build fingerprint: 'samsung/hero2ltexx/hero2lte:6.0.1/MMB29K/G935FXXU1APDU:user/release-keys'
pid: 485, tid: 1064, name: SDLThread >>> org.easyrpg.player <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x38
Stack frame #00 pc 00132d9c /data/app/org.easyrpg.player-1/lib/arm/libmain.so: Routine Game_BattleAlgorithm::AlgorithmBase::IsFirstAttack() const at /var/lib/jenkins/workspace/player-android/builds/android/app/src/main/jni/src/../../../../../../..//src/game_battlealgorithm.cpp:167
Stack frame #01 pc 00180bcb /data/app/org.easyrpg.player-1/lib/arm/libmain.so (_ZN18Scene_Battle_Rpg2k19ProcessBattleActionEPN20Game_BattleAlgorithm13AlgorithmBaseE+394): Routine Scene_Battle_Rpg2k::ProcessBattleAction(Game_BattleAlgorithm::AlgorithmBase*) at /var/lib/jenkins/workspace/player-android/builds/android/app/src/main/jni/src/../../../../../../..//src/scene_battle_rpg2k.cpp:381
Stack frame #02 pc 00182efb /data/app/org.easyrpg.player-1/lib/arm/libmain.so (_ZN18Scene_Battle_Rpg2k14ProcessActionsEv+406): Routine Scene_Battle_Rpg2k::ProcessActions() at /var/lib/jenkins/workspace/player-android/builds/android/app/src/main/jni/src/../../../../../../..//src/scene_battle_rpg2k.cpp:265
Stack frame #03 pc 0017ba91 /data/app/org.easyrpg.player-1/lib/arm/libmain.so (_ZN12Scene_Battle6UpdateEv+360): Routine Scene_Battle::Update() at /var/lib/jenkins/workspace/player-android/builds/android/app/src/main/jni/src/../../../../../../..//src/scene_battle.cpp:163
Stack frame #04 pc 0015dabf /data/app/org.easyrpg.player-1/lib/arm/libmain.so (_ZN6Player6UpdateEb+206): Routine Player::Update(bool) at /var/lib/jenkins/workspace/player-android/builds/android/app/src/main/jni/src/../../../../../../..//src/player.cpp:338
Stack frame #05 pc 00183219 /data/app/org.easyrpg.player-1/lib/arm/libmain.so (_ZN5Scene12MainFunctionEv+152): Routine Scene::MainFunction() at /var/lib/jenkins/workspace/player-android/builds/android/app/src/main/jni/src/../../../../../../..//src/scene.cpp:98
Stack frame #06 pc 0015dd4b /data/app/org.easyrpg.player-1/lib/arm/libmain.so (_ZN6Player8MainLoopEv+26): Routine Player::MainLoop() at /var/lib/jenkins/workspace/player-android/builds/android/app/src/main/jni/src/../../../../../../..//src/player.cpp:263
Stack frame #07 pc 0015deed /data/app/org.easyrpg.player-1/lib/arm/libmain.so (_ZN6Player3RunEv+232): Routine Player::Run() at /var/lib/jenkins/workspace/player-android/builds/android/app/src/main/jni/src/../../../../../../..//src/player.cpp:258
Stack frame #08 pc 00153ecf /data/app/org.easyrpg.player-1/lib/arm/libmain.so (SDL_main+14): Routine SDL_main at /var/lib/jenkins/workspace/player-android/builds/android/app/src/main/jni/src/../../../../../../..//src/main.cpp:33
Stack frame #09 pc 0011038f /data/app/org.easyrpg.player-1/lib/arm/libmain.so (Java_org_libsdl_app_SDLActivity_nativeInit+206): Routine Java_org_libsdl_app_SDLActivity_nativeInit at /var/lib/jenkins/workspace/player-android/builds/android/app/src/main/jni/src/SDL_android_main.c:62
Stack frame #10 pc 00036f39 /data/app/org.easyrpg.player-1/oat/arm/base.odex (offset 0x26000)
```

### PR DESCRIPTION
**Pull request by Ghabry**
1) Segfault when selecting a previous actor when one of the skipped actors was dead.
2) The wrong battle algorithm was removed (from the front, but actually the latest is at the back). This is the famous "Has no action but got a turn"-bug.

Fix #933

I removed the sanity check because the only way to trigger this is a bug in the code (which is found now).

### CODE REVIEW

File: src/scene_battle_rpg2k.cpp [hunk 1]
```diff
@@ -742,14 +736,16 @@ void Scene_Battle_Rpg2k::SelectPreviousActor() {
...
 	actor_index--;
-	RemoveCurrentAction();
 	active_actor = allies[actor_index];
 
 	if (active_actor->IsDead()) {
 		SelectPreviousActor();
 		return;
 	}
 
+	battle_actions.back()->SetBattleAlgorithm(std::shared_ptr<Game_BattleAlgorithm::AlgorithmBase>());
```
Comment (fdelapena) [inline src/scene_battle_rpg2k.cpp]: Could battle_actions be empty here?

Comment (Ghabry) [inline src/scene_battle_rpg2k.cpp]: No, the cases "dead" and "first actor" are handled a few lines above.
