### PR TITLE
Battle 2k3: Implement in-battle row command

### LINKED ISSUE #680: Embric of Wulfhammer's Castle: "Row" battle command is missing
With bug #601 having been fixed, most of the commands are now correctly shown and usable in git. However, one of the commands, 'Row' is still missing.

Steps to reproduce:
- Download game ( http://aeresland.net/EmbricDELUXE_2.2.2.7z )
- Download my savegame from http://www.heavylobster.com/files/Save03.lsd
- Take one step north to enter combat
- Select 'strategize'. The 'Row' command, which is present on RPG_RT, is missing from the list. Note that even on RPG_RT, you need to scroll down in the list to actually see it.

### PR DESCRIPTION
**Pull request by rueter37**
This PR adds the in-battle row command used in RPG Maker 2003. Merging this PR and #2321 into master fixes #680.

### CODE REVIEW

File: src/scene_battle_rpg2k3.cpp [hunk 1]
```diff
@@ -1277,6 +1284,30 @@ void Scene_Battle_Rpg2k3::SpecialSelected() {
...
+void Scene_Battle_Rpg2k3::RowSelected() {
+	// Switching rows is only possible if in back row or
+	// if at least 2 party members are in front row
+	int current_row = active_actor->GetBattleRow();
+	int front_row_battlers = 0;
+	if (current_row == Game_Actor::RowType::RowType_front) {
+		for (auto& actor: Main_Data::game_party->GetActors()) {
+			if (actor->GetBattleRow() == Game_Actor::RowType::RowType_front) front_row_battlers++;
+		}
+	}
```
Comment (fmatthew5876) [inline src/scene_battle_rpg2k3.cpp:1296]: This case doesn't appear to handle back attacks etc..

I checked in RE tools and found that RPG_RT checks `row == mirrored` to mean front `row != mirrored` where you say back.

**Comment by fmatthew5876** [comment]
For bonus points, are you bug compatible with this?

https://github.com/EasyRPG/Player/issues/1486#issuecomment-441373701

😄

**Comment by rueter37** [comment]
Okay, that thing mentioned in [#1486](https://github.com/EasyRPG/Player/issues/1486#issuecomment-441373701) is a really crazy one. I have tried to reproduce that bug in RPG_RT without avail. Probably I'm missing something obvious. But do we want to emulate that bug? I'm pretty sure the implementation in this PR doesn't.

File: src/scene_battle_rpg2k3.cpp (hunk 1 above)
Comment (rueter37) [reply src/scene_battle_rpg2k3.cpp:1296]: Did the change as requested and tested it. I have amended the commit and force pushed it because I assume you want this in one commit.

**Comment by fmatthew5876** [comment]
I don't care about the bug it's dumb and better we fix it. 

I suspect it's because you reset the actor position after processing row command. RPG_RT just adds or subtracts 24 from x.

**Comment by rueter37** [comment]
Then we are all set!

**Review by fmatthew5876 — APPROVED** [review]

File: src/scene_battle_rpg2k3.cpp [hunk 2]
```diff
@@ -1461,8 +1492,14 @@ void Scene_Battle_Rpg2k3::ActionSelectedCallback(Game_Battler* for_battler) {
...
 	if (for_battler->GetType() == Game_Battler::Type_Ally) {
-		const lcf::rpg::BattleCommand* command = static_cast<Game_Actor*>(for_battler)->GetBattleCommands()[command_window->GetIndex()];
-		for_battler->SetLastBattleAction(command->ID);
+		int index = command_window->GetIndex();
+		// Row command always uses the last index
+		if (index < command_window->GetRowMax() - 1) {
+			const lcf::rpg::BattleCommand* command = static_cast<Game_Actor*>(for_battler)->GetBattleCommands()[index];
+			for_battler->SetLastBattleAction(command->ID);
+		} else {
+			for_battler->SetLastBattleAction(-1);
```
Comment (Ghabry) [inline src/scene_battle_rpg2k3.cpp:1501]: This must be verified because the last battle action is a battle page start condition (or was it a condition in a conditional branch?). So this value must match.
Even if the row command can't be picked there through the editor I bet there is at least one game that patched the value and checks for it (see Change Vehicle position with -1)

Comment (Ghabry) [reply src/scene_battle_rpg2k3.cpp:1501]: -1 is indeed the Row command, just tested this via LDB-patching :thinking:

Comment (fmatthew5876) [reply src/scene_battle_rpg2k3.cpp:1501]: I'm not sure it's actually -1. The logic I've seen in RPG_RT is usually something like this:

```
auto* batcmd = GetBattleCommandByIndex(window->currentchoice);
if (batcmd) {
  switch(batcmd->type) {
    // Handle each command
  }
} else {
  // Handle row command
}
```

What if you try -2 or a large value greater than the number of configured battle commands?

Comment (Ghabry) [reply src/scene_battle_rpg2k3.cpp:1501]: I only tested -1 and -2. -2 didn't activate my event page.

**Review by fdelapena — APPROVED** [review]

File: src/scene_battle_rpg2k3.cpp (hunk 2 above)
Comment (Ghabry) [reply src/scene_battle_rpg2k3.cpp:1501]: Figured it out by now: That's (kinda) a bug. Only kinda because this needs external tools to be utilized:

The ``GetBattleCommandByIndex`` function checks if the cmd idx is ``>= 6`` and if yes it returns ``-1``.
Otherwise it resolves the battle command of the actor. For the row this is ``0``.

Conclusion:
When an actor has 6 battle commands then row has an action ID of -1, otherwise it has an action ID of 0.

@rueter37 can you implement this behaviour? (``SetLastBattleAction(-1)`` for "6 cmds``, else ``SetLastBattleAction(-1)``)

Comment (rueter37) [reply src/scene_battle_rpg2k3.cpp]: Added the LastBattleAction changes.
