### PR TITLE
Fix #1002 (Aurora Wing). Limit the variable range to [-999999,999999] for RPG Maker 2000 games.

### LINKED ISSUE #1002: Aurora Wing: Intro has a skippable hang and first battle gets stuck after enemy turn
Aurora Wing is some Fire Emblem clone.

Download: https://rpgmaker.net/games/42/downloads/27/

Web testcase: https://easy-rpg.org/play/master/?game=aurora_wing
- [X] Intro hangs directly after the options menu shown at the beginning (Intro can be skipped with CANCEL)
- [x] after the (super slow) turns of the enemy the player does not get a turn.

Looks like "MakeWay" can't make way and therefore all movements fail.

Probably a problem with diagonal movements.

### PR DESCRIPTION
**Pull request by Ghabry**
-

### CODE REVIEW

File: src/game_interpreter.h [hunk 1]
```diff
@@ -64,8 +64,10 @@ class Game_Interpreter
 	virtual bool ExecuteCommand();
 
 	enum Sizes {
```
Comment (carstene1ns) [inline src/game_interpreter.h]: C++11 allows typed enums, this might help not needing the cast to `int` later.
