### PR TITLE
Switch + macOS fix

### LINKED ISSUE #1994: Update Switch build for new libnx
At least `threadCreate()` needs additional `NULL` argument.

### PR DESCRIPTION
**Pull request by carstene1ns**
Fixes #1994.

### CODE REVIEW

File: src/audio_switch.cpp [hunk 1]
```diff
@@ -84,7 +84,7 @@ NxAudio::NxAudio() :
 	
 	mutexInit(&audio_mutex);
 
-	threadCreate(&audio_thread, switch_audio_thread, NULL, 0x10000, 0x2B, -2);
+	threadCreate(&audio_thread, switch_audio_thread, NULL, NULL, 0x10000, 0x2B, -2);
```
Comment (fmatthew5876) [inline src/audio_switch.cpp]: Should use `nullptr`

Comment (carstene1ns) [reply src/audio_switch.cpp]: Yeah, should be used in other places as well. Just using it for consistency.

**Comment by Ghabry** [comment]
reran OSX builder: Works :+1: 

The NULL stuff is unfortunate but this goes through all of the DisplayUi stuff, so changing it at one line will not help much.
