### PR TITLE
Battle 2k3: Bugfixes

### LINKED ISSUE #1490: Abnormal state
Thank you for supporting EasyRPG Player.
Before creating an issue, please verify that your bug still occurs in the "continuous builds" of the Player.
You can get them at the bottom of our download section: https://easyrpg.org/player/downloads

---
Please fill in the following fields before submitting an issue:
#### Player platform:Android
Windows, Linux, Android, ...

#### Attach files (as a .zip archive or link them)
 - A savegame next to the problem (if it is not at the beginning of the game)
www.mediafire.com/file/k0969lkmqqax6hu/
 - The `easyrpg_log.txt` log file (you can find it in the game directory)

#### Describe the issue in detail and how to reproduce it:

Life recovery and mana recovery turns to decrease instead

### PR DESCRIPTION
**Pull request by Ghabry**
~~Don't merge yet, the heal/inflict logic still has some bug. I know where it is but touching battle at this time of the day is a bad idea~~ Decided to not fix this for skills, battlealgortihm needs a refactor first

and in #821 it ticks one more option:
- Items (Other): The 2nd option (heal instead of inflict) for states

This isn't really a battle thing, this just means that the item causes a permanent state that can't be removed except by unequipping.

Also improved the equip sanity check, handles now more corner cases.

### CODE REVIEW

File: src/game_actor.cpp [hunk 1]
```diff
@@ -325,16 +334,55 @@ void Game_Actor::AddState(int state_id) {
 
 void Game_Actor::RemoveState(int state_id) {
 	Game_Battler::RemoveState(state_id);
+	AddEquipmentStates();
 }
 
 void Game_Actor::RemoveBattleStates() {
 	Game_Battler::RemoveBattleStates();
+	AddEquipmentStates();
```
Comment (Ghabry) [inline src/game_actor.cpp]: Todo: AddEquipmentStates only needed in RemoveState, all code paths go through it (except RemoveAllStates, refactor?)

File: src/game_battlealgorithm.cpp [hunk 2]
```diff
@@ -1215,7 +1216,16 @@ bool Game_BattleAlgorithm::Skill::Execute() {
 		skill.scope == RPG::Skill::Scope_party ||
 		skill.scope == RPG::Skill::Scope_self;
 
-	this->revived = this->healing
+	bool heals_states = this->healing;
```
Comment (fmatthew5876) [inline src/game_battlealgorithm.cpp]: At some point I'd like to get rid of the `healing` and `positive` concepts here. Battle actions should be more general and just have effects (+-stats, inflict/heal states, etc..)

**Comment by fmatthew5876** [comment]
Just a general comment.

It sounds like this could be exploited. Say you had an armor that inflicted poison. It sounds like whenever someone gets poisoned in battle, you could just equip and then unequip that armor to remove the poison.

File: src/game_battlealgorithm.cpp [hunk 3]
```diff
@@ -1190,7 +1190,8 @@ bool Game_BattleAlgorithm::Skill::IsTargetValid() const {
 		skill.scope == RPG::Skill::Scope_party) {
 		if (GetTarget()->IsDead()) {
 			// Cures death
-			return !skill.state_effects.empty() && skill.state_effects[0];
+			return !skill.state_effects.empty() && skill.state_effects[0] &&
+				!(Player::IsRPG2k3() && skill.state_effect);
 		}
```
Comment (fmatthew5876) [inline src/game_battlealgorithm.cpp]: I'd actually like to see this feature as an EasyRPG extension to 2k battle system. But that can be added later.

File: src/game_actor.cpp (hunk 1 above)
Comment (fmatthew5876) [reply src/game_actor.cpp]: Instead of removing and adding the states back, would it make more sense to just filter in the remove? Like `if (!isEquipState(state)) Game_Battler::RemoveState(state);`

**Comment by Ghabry** [comment]
> It sounds like this could be exploited

Yepp that's exactly how my test cases looked. Another 2k3 feature with bad execution.
When you have a "dead bringing shield" you can even revive actors by equipping and unequipping.
Imo this is only usable in combination with curse.

File: src/game_battlealgorithm.cpp (hunk 2 above)
Comment (Ghabry) [reply src/game_battlealgorithm.cpp]: Healing and positive really don't work. Won't touch this here, too easy to break, but this needs a refactor

**Comment by Ghabry** [comment]
The "Equipment that gives states" had many interesting corner cases but I think I got all.
E.g. a state with "persists after battle" set to false is not inflicted on the map but on battle start.

I also fixed a 2k3 bug: The Equipment scene ignores half/double stats when showing the preview.

**Comment by fmatthew5876** [comment]
> I also fixed a 2k3 bug: The Equipment scene ignores half/double stats when showing the preview.

I guess this one is sort of debatable.

If I equip some armor with double stats, it looks very good but now I can't be buffed with double stat skills as they don't stack. Similar for half stat effects.

I'm not sure whats the best option here. To display or not.

**Comment by Ghabry** [comment]
Well the equipment scene in RPG 2k3 will update as soon as you equip it. So imo this is a visual glitch because the buff is shown, just not in the preview :/

**Comment by fmatthew5876** [comment]
I see what you mean, in that case I agree with you.

**Comment by fmatthew5876** [comment]
Do you feel confident about no regressions? Since its a new feature and not a bug fix, maybe its safer to postpone to after the release?

**Comment by carstene1ns** [comment]
I agree with @fmatthew5876 here, this looks like it could cause problems.
Maybe keep c73f9f67b6c9 until after release and only apply the rest?

**Comment by Ghabry** [comment]
I feel condident with this one but I agree with your observation that this commit is far too complex for one day before release.
