### PR TITLE
Move Route refactors

### LINKED ISSUE #1267: Enter Vehicle fails when the Vehicle is entered through EnterVehicle while a move route is active
Test case: https://easyrpg.org/play/?game=issue-1267
Press SHIFT, Alex should move into the sky.

The problem is that our "GetOnOffVehicle" checks for "IsMovable" and one case of is movable is: MoveRouteOverwritten. Which is the case in this game.

In RPG_RT the move route actually continues after entering the vehicle.

### LINKED ISSUE #1293: Ascendence: Visual bugs
#### Name of the game:
Ascendence RSD VI - https://rpgmaker.net/games/736/downloads/

#### Player platform:
Windows (32 bit) - Continuous build

#### Attach files
save

#### Issues:
- [X] Slight animation bugs in intro for characters Kell and Velto (pulling animation, walking headbob hair) (**fixed in #1601 for 0.6.1**)
- [X] City intro fade-in is too quick compared to original
- [x] Screen shake for first elevator is not emulated (**fixed in 0.6**)
- [X] Strange red box around player when entering/leaving save zone (see gif)

### LINKED ISSUE #1346: Script for 8-way movement not smooth in EasyRPG
#### Name of the game:
Test Project

#### Player platform:
Windows 32 & 64-Bit

#### Attached files:
https://www.dropbox.com/s/vcchdiyqiom6eow/Project1.zip?dl=1

Log :
```
[2018-03-27 08:08:22] Debug: EasyRPG Player 0.5.3 (git~73@0220488, 2018-03-09) started
[2018-03-27 08:08:22] Debug: =========================================================
[2018-03-27 08:08:22] Debug: CLI: 
[2018-03-27 08:08:22] Debug: Opened audio at 44100 Hz (stereo), format: S16LSB
[2018-03-27 08:08:22] Debug: Cannot find: Title/Title1 (!)
[2018-03-27 08:08:22] Debug: Detected encoding: ibm-5348_P100-1997. Files not found. Trying next.
[2018-03-27 08:08:22] Debug: Cannot find: Title/Title1 (!)
[2018-03-27 08:08:22] Debug: Detected encoding: UTF-8. Files not found. Trying next.
[2018-03-27 08:08:22] Debug: Cannot find: Title/Title1 (!)
[2018-03-27 08:08:22] Debug: Detected encoding: ibm-5346_P100-1998. Files not found. Trying next.
[2018-03-27 08:08:22] Debug: Cannot find: Title/呩瑬攱 (!)
[2018-03-27 08:08:22] Debug: Detected encoding: UTF-16BE. Files not found. Trying next.
[2018-03-27 08:08:22] Debug: Cannot find: Title/楔汴ㅥ (!)
[2018-03-27 08:08:22] Debug: Detected encoding: UTF-16LE. Files not found. Trying next.
[2018-03-27 08:08:22] Debug: Bad encoding: ISO-8859-9. Trying next.
[2018-03-27 08:08:22] Debug: Cannot find: Title/Title1 (!)
[2018-03-27 08:08:22] Debug: Detected encoding: ibm-943_P15A-2003. Files not found. Trying next.
[2018-03-27 08:08:22] Debug: Cannot find: Title/Title1 (!)
[2018-03-27 08:08:22] Debug: Detected encoding: windows-936-2000. Files not found. Trying next.
[2018-03-27 08:08:22] Debug: Bad encoding: EUC-JP. Trying next.
[2018-03-27 08:08:22] Debug: Cannot find: Title/Title1 (!)
[2018-03-27 08:08:22] Debug: Detected encoding: windows-949-2000. Files not found. Trying next.
[2018-03-27 08:08:22] Debug: Cannot find: Title/Title1 (!)
[2018-03-27 08:08:22] Debug: Detected encoding: Big5. Files not found. Trying next.
[2018-03-27 08:08:22] Debug: Bad encoding: IBM424_ltr. Trying next.
[2018-03-27 08:08:22] Debug: Bad encoding: IBM424_rtl. Trying next.
[2018-03-27 08:08:22] Debug: Detected encoding: ibm-5348_P100-1997
[2018-03-27 08:08:22] Debug: Using . as Game and Save directory
[2018-03-27 08:08:22] Debug: Loading game Untitled
[2018-03-27 08:08:22] Debug: Using RPG2k3 (English release, v1.11) Interpreter
[2018-03-27 08:08:22] Debug: RPG2k >= v1.50 / RPG2k3 >= v1.05 detected
[2018-03-27 08:08:22] Debug: Engine configured as: 2k=0 2k3=1 2k3Legacy=0 MajorUpdated=1 Eng=1
[2018-03-27 08:08:22] Debug: Adding C:\Program Files (x86)\Steam\steamapps\common\RPG Maker 2003\RTP to RTP path
[2018-03-27 08:08:22] Debug: Adding C:\Program Files (x86)\rpg2003\RTP to RTP path
[2018-03-27 08:08:22] Debug: Actor 1: Removing invalid item 44 (of type 2) from equipment slot 2 (needs type 1)
[2018-03-27 08:08:23] Debug: libpng: iCCP: known incorrect sRGB profile
[2018-03-27 08:08:23] Debug: libpng: cHRM: inconsistent chromaticities
[2018-03-27 08:08:25] Debug: Starting new game
[2018-03-27 08:08:25] Debug: Loading Map Map0001.lmu
[2018-03-27 08:08:25] Debug: Tree: MAP0001
[2018-03-27 08:08:36] Debug: Actor 1: Removing invalid item 44 (of type 2) from equipment slot 2 (needs type 1)
```

#### Video showcasing issue:
[](url)https://youtu.be/5m9MSr2wX10

#### Description:
This is an event allowing for 8-way movement. it works fine in the regular RM2k3, but as of march 26, 2018, the movement is not in the latest continuous version of EasyRPG. Maybe it has to do with the "Wait for All Movement" command.

### LINKED ISSUE #1429: EasyRPG's "disembark vehicle" cmd doesn't operate the same as RM2K's
Tested in the stable version and in a more recent dev build (2aa5292). Same version I used to test my last bug.

This affects a game I was playing but I've made a minimal test case that reproduces the problem.

---

#### Name of the game:
Vehicle test

#### Player platform:
OSX

#### Attach files (as a .zip archive or link them)
 - [Vehicle.zip](https://github.com/EasyRPG/Player/files/2450919/Vehicle.zip)
 - [easyrpg_log](https://gist.github.com/msikma/cb695910be988891e95a0ffbc6436a4e)

#### Describe the issue in detail and how to reproduce it:

The player is on a boat, sailing on the water. You hit an event and the following commands are executed:

- Move boat left, left, face up (the exact movement commands don't really matter, as long as you can walk a few tiles)
- Ride/Disembark vehicle

In RM2k, the "disembark vehicle" command is executed immediately, before the move command is over. After disembarking it's the hero character that performs the move command.

This appears to only occur when the event is placed by the shore so that disembarking is possible right at the start.

RM2k: disembark, then hero walks left two tiles and faces up.

screen shot 2018-10-05 at 17 13 08

EasyRPG: does not disembark, boat goes left two tiles and faces up.

screen shot 2018-10-05 at 17 21 38

In the game I was playing this led to me being teleported to another map while still being a boat. 😄

### LINKED ISSUE #1585: Events with Spin restart their animation when write any command and interact with it
**Tested in** : Player 0.5.4 (continuous).
**How to reproduce it**: Create a new event with animation type "Spin" and write any command in it.
**Platform**: Windows 7 (x64)

**Test case**:
[Restart spin](https://github.com/EasyRPG/Player/files/2820060/TestCase.-.Event-Spin.zip)

### LINKED ISSUE #1587: Error to changing an event graphic using event pages (missing and wrong graphics)
**Tested in**: Player 0.5.4 (continuous).
**How to reproduce it**: Create an event with several pages and graphics (fixed graphic). A parallel process event will change among pages using variables and will make "Set Move Route".
**Platform**: Windows 7 (x64)

**Test case**:
[Changing charset graphic via event pages](https://github.com/EasyRPG/Player/files/2820062/TestCase.-.Change.events.graphic.zip)

### LINKED ISSUE #1593: Lakria Legends: Movement hangs on the ramp
via Android bug reporting.

#### Name of the game: [Lakria Legends](https://rpgmaker.net/games/5562/downloads/9559/)  
Yet another REFMAP RPG

#### Describe the issue in detail and how to reproduce it:

Start with ``--new-game --start-map-id 18 --start-position 17 5``

Walk on the ramp and the game will get stuck in an endless movement uphill/downhill loop.

Quick event analysis:

Start conditions are "event touch"

```
Top ramp event: (disabled when Going Up = ON)
@> Set Move Route: Player, Turn Right
@> Control Switches: [0032:Going Down] = ON
@> Set Move Route: Player, Move Bottom Right, Move Bottom Right
@> Control Switches: [0032:Going Down] = OFF

Bottom ramp event: (disabled when Going Down = ON)
@> Set Move Route: Player, Turn Left
@> Control Switches: [0031:Going Up] = ON
@> Set Move Route: Player, Move Upper Left, Move Left
@> Control Switches: [0031:Going Up] = OFF
```

The switch toggling is obviously a red hering, the switch is already OFF again when the movement starts. Can be deleted, result is the same.

Basicly the other ramp event is touched while moving and this triggers the downwards movement.

We already ignore "Player touch" events when a move route is active (matches RPG_RT), maybe the same must be done for "Event touch"? Needs testing. (Changing the events from Event to Player touch fixes it in Player).

Note: Event Touch is CheckCollisionEvent() in Game_Player

### LINKED ISSUE #1604: Move towards player move route is wrong
There are 2 kinds of "move to player" movements.

There is `move_type == toward`. This one will move to the player but also dodge obstacles

Then there is move commands to "Step Towards Player" commands. These are dumb, in that they will only try to step to the player and fail if anything is in the way.

In Player, both behave like the `move_type` case.

### LINKED ISSUE #1654: Manually spin event is not working
Create 2 events, one of them a charset with the graphic (the event to animate), the other one as parallel process with:

> @> Wait: 0.5 seconds
@> Set Move Route: [Event to animate], Turn Right
@> Wait: 0.3 seconds
@> Set Move Route: [Event to animate], Turn Down
@> Wait: 1.5 seconds
@> Set Move Route: [Event to animate], Turn Left
@> Wait: 0.3 seconds
@> Set Move Route: [Event to animate], Turn Up

In my case, the result is the charset graphic stay in the center position without animation.

### LINKED ISSUE #1671: Enemies stay "hooked" unlimitedly in KangaPunch mini-game
There's a new problem in this mini-game with Player 0.6

In RPG_RT, the kangaroo can "hook" the enemy when the enemy is blocking hits for a limited time, in EasyRPG this hook is until the enemy is K.O.

(This is not intentional, it's the normal behavior of events in RPG_RT)

How to reproduce it: especially with Happy Hippo (it's the more defensive enemy), launch punches when the enemy is moving until the enemy stay blocking hits during a time, then, the enemy will move in other direction and going forward the kangaroo again.

Here you can see the difference:

RPG_RT
https://youtu.be/rFYmSVbPHOc

Player
https://youtu.be/yWgGdY4miho

### PR DESCRIPTION
**Pull request by fmatthew5876**
This PR is refactor `SaveMapEventBase` move route related chunks to behave more like `RPG_RT` and improve support loading save games correctly on any frame of movement.

This still needs a lot more testing and probably more changes to be correct. 

Detailed test cases and research can be found in #1567

Fix #1267 
Fix #1293
Fix #1346
Fix #1429
Fix #1585
Fix #1587
Fix #1593
Fix #1604
Fix #1654
Fix #1671

Breaks #579
Breaks #937

Behaviors of `stop_count`
- [x] Continues ticking through the end of the last move route command into infinity, does not reset
- [x] Resets every time the player takes a step from the keyboard
- [x] Initialized to 0 on the first frame of a new game
- [x] Does not reset when we change maps
- [x] Move route advances *after* `stop_count == max_stop_count`
- [x] Initialized to `65535` when a `SetMoveRoute` command is processed.
- [x] Initialized to `0` when the next move command is processed, and then advances to `1` on the same frame.
- [x] Move routes are not processed on the first frame of a new map, and so `stop_count` will not tick for the first frame. This means it'll be `0` if on the first frame you do have a parallel event do `OpenSaveMenu` or `65535` if you do `SetMoveRoute, OpenSaveMenu`. The behavior affects the Player and Vehicles but not map events! :question: 
- [x] `stop_count` ticks while any (player, event, or vehicle) is idle and has no move route, unless an event is active in the foreground (autostart, talk).
- [x] Does not tick for vehicles not on the current map. Stays frozen to whatever the previous value was when you teleport away from a map that had the vehicle.
- [x] Does not tick for events which don't have any active page.
- [x] If the last move command is a step, we ignore `max_stop_count` and cancel the move route as soon as the move finishes, reseting back to idle state.
- [x] If the last move command is a jump, we ignore `max_stop_count` and cancel the move route as soon as the move finishes, reseting back to idle state.
- [x] When player `vehicle > 0` and `aboard = 1`, that vehicle `stop_count` is frozen.
- [x] Does not change when you talk to an event and that event changes direction (or doesn't change)
- [x] SetEventLocation and SetVehicleLocation do not reset `stop_count`
- [x] Teleport does not reset `stop_count`

Behaviors of `max_stop_count`
- [x] Player and vehicle initialized to 0 on new game.
- [x] Map event initialized to stepping value of event's `move_frequency`.
- [x] Step: `move_frequency == 8 ? 0 : (2 ^ (9 - move_frequency))`
- [x] Turn: `move_frequency == 8 ? 0 : (2 ^ (8 - move_frequency))`
- [x] Wait: `20 + (move_frequency == 8 ? 0 : (2 ^ (8 - move_frequency)))`
- [x] When a `SetMoveRoute` command is processed, initialized to stepping value for the `move_frequency` of the move route.
- [x] After move route finishes, resets to stepping value of the `original_move_frequency`
- [x] Does not change when the player steps from player controls (remains 0 when walking around after new game, or 128 when walking around after the Player has had 1 move route since the game started).

Behaviors of `move_frequency`
- [x] Player defaults to 2 (empty chunk) and resets to 2 after move route finishes
- [x] Vehicle defaults to 2 (empty chunk) and resets to 2 after move route finishes
- [x] Event defaults to active page move_frequency and resets to it after move route finishes 
- [x] Event defaults to 2 (empty chunk) if no active page
- [x] When loading a save during an active move route, Player `move_frequency` resets to 0 after the move route finishes. (RPG_RT bug)
    - [x] Fixed in Player
- [x] When loading a save during an active move route, Vehicle `move_frequency` resets to 0 after the move route finishes. (RPG_RT bug)
    - [x] Fixed in Player
- [x] Increase/decrease frequency commands don't last after move route finishes

Behaviors of `move_commands`
- [x] Populated with array of commands when move route starts
- [x] Not cleared after move route finishes. Remains forever until next move route.

Behaviors of `move_route_index`
- [x] Starts at 0
- [x] Resets to 0 when new move route starts
- [x] When move command is being processed, points to the next move command, or `move_commands.size()` if this is the last move command.
- [x] If the last move command is a step, resets to 0 when move route finishes
- [x] If the last move command is not a step, remains unchanged when move route finishes

Behaviors of `move_route_overwrite`
- [x] Set 1 when move route starts
- [x] Set to 0 on the frame after move route finishes

Behaviors of `jumping`
- [x] Set to 1 on the frame the jump starts
- [x] Set to 0 on the last frame of the jump (when remaining_step = 0). This is different than most things which trigger on the frame after the movement.
- [x] SetEventLocation and SetVehicleLocation do not reset `jumping` (RPG_RT bug :exclamation: )
    - [x] Fixed in Player
- [x] Teleport does not reset `jumping` (RPG_RT bug :exclamation: )
    - [x] Fixed in Player

Behaviors of `remaining_step`
- [x] SetEventLocation and SetVehicleLocation reset `remaining_step`
- [x] Teleport resets `remaining_step`

Behaviors of `anim_count`
- [x] When `animation_type` is `fixed_graphic` or `step_frame_fix`, `anim_count` is always 0.
- [x] limit non-continuous = [11, 9, 7, 5, 4, 3] (based on `move_speed`)
- [x] limit continuous = [15, 11, 9, 7, 6, 5] (based on `move_speed`)
- [x] limit spin = [23, 14, 11, 7, 5, 3] (based on `move_speed`)
- [x] When anim_count reaches appropriate limit, either freezes there or increments `anim_frame` and goes back to 0. (see cases below)
- [x] when event `animation_type` is non_continous, `remaining_step=0`, and `anim_frame=1 or 3`, `anim_count` counts up to the non_continuous limit and then freezes there.
- [x]  when event `animation_type` is non_continous, `remaining_step=0`, and `anim_frame=0 or 2`, `anim_count` counts up to the continuous limit and then `anim_frame` cycles to the next value (1 or 3)
- [x]  when event `animation_type` is continous, `remaining_step=0`, `anim_count` counts up to the continuous limit and then `anim_frame` cycles to the next value
- [x] When `remaining_step > 0`, `anim_count` counts up to the non_continuous limit and then `anim_frame` cycles to the next value. Note that `remaining_step` decrements first, so this rule relies on the `remaining_step` value at the beginning of this frame.
- [x] Decreasing `move_speed` will cause `anim_count` to increment further as the limit increases.
- [x] Increasing `move_speed` will reduce the limit but `anim_count` will not change.
- [x] If you increase the `move_speed` enough that your current `anim_count` is now above the continuous limit for the new speed, the `anim_frame` will increment. #663 
- [x] Setting a tile graphic doesn't change anything.
- [x] Change graphic move command has no effect on animations.
- [x] When `jumping=1`, then we force `anim_count=0` and `anim_frame=1`. This means when a jump is started, the animation resets.
- [x] On the last frame of the jump, `jumping=0` and `anim_count=1`. That is, the `anim_count` starts ticking on the last frame of the jump, instead of waiting for the next frame to start.
- [x] When no event page is active, `anim_count=0` and `anim_frame=1`
- [x] SetEventLocation and SetVehicleLocation do not reset `anim_count`
- [x] Teleport resets `anim_count`
- [x] Is reset when `anim_paused=1`

Behaviors of `anim_frame`:
- [x] 0 = Left
- [x] 1 = Middle
- [x] 2 = Right
- [x] 3 = Middle
- [x] Defaults to 1, and then cycles 1, 2, 3, 0, 1, 2, 3, 0, ... as mentioned above in `anim_count` cases.
- [x] SetEventLocation and SetVehicleLocation do not reset `anim_frame`
- [x] Teleport resets `anim_frame`
- [x] Is reset when `anim_paused=1`

Animation of Vehicles:
- [x] Boat and Ship limit is always 15 regardless of `move_speed` and always continuously animating `anim_frame` to this.
- [x] Airship `anim_count=0` and `anim_frame=1` while `aboard=0`. This includes getting reset when landing
- [x] Airship limit is 11 and continuously animates while boarded
- [x] No change when player boards a vehicle, except the move speed of the vehicle (airship) can change how the animation continues as described above.
- [ ] If you put any move route on the airship, it's `anim_count` limit changes to 15 instead of 11 and seems to stay there forever. If you quit and load and saved game it goes back to 11 until you make a new move route. RPG_RT bug?? :exclamation: 

Behaviors of spinning events:
- [x] Spinning animation only changes `sprite_direction`.
- [x] A Turn move command changes both `direction` and `sprite_direction`
- [x] If a Turn move command is started on the same frame as animation, the `direction` will be of the turn, and `sprite_direction = (direction + 1) % 4`
- [x] A Move move command changes only `direction`
- [x] Triggering a spinning event via Action, Player Touch, or Event Touch does not affect `direction` or `sprite_direction`
- [x] When a jump is started, both `direction` and `sprite_direction` are set in the direction of the jump
- [x] When a jump is in progress, the spin will still continue to animate.
- [x] If a jump is started on the same frame as animation, the `direction` will be of the jump, and `sprite_direction = (direction + 1) % 4`

Player Controls:
- [x] Player controls don't respond until movement and `stop_count` of last move command finishes.

Vehicle Move Route interactions:
- [x] Airship move route gets canceled 1 frame after player boards
- [x] An active Boat, Ship move route gets canceled when player finishes boarding and `aboard` is set to 1.
- [x] Boat, Ship position fixed to player position when boarding finishes. This can be seen by moving the ship with a move route while the player is boarding.
- [x] If `Player::vehicle > 0`, SetMoveRoute against that vehicle gets applied to the player instead
- [x] If a move route gets set on the player while boarding, it will wait until the player finishes boarding and then execute on the player in the vehicle.

TBD:
- [x] How overwritten move route interacts with Event original move_route
- [x] Behavior of counters when move fails
- [x] Devirtualize GetOriginalMoveRouteIndex()
- [x] Don't store copy of original_move_route
- [x] When active move route is interrupted by another move route
- [x] How move route interacts with teleport
- [x] How move route interacts with get on/off vehicle  #1429
- [x] Investigate `through` and `route_through` behavior when getting on/off vehicles
- [x] Effect of Erase Event and disabling all active pages. What happens when you do this mid move, `stop_count`, `anim_count`, etc...?
- [x] Effect of changing the active event page in the middle of a move or wait? Animations?
- [x] Effect of Animation Off move command during different animation frames.
- [x] Effect of failed jump on animation
- [x] Effect of wait for all movement
- [x] Effect of stop all movement
- [x] Effect of `move_type=random`

Please post more test cases if you can think of any not here.

### CODE REVIEW

**Comment by Ghabry** [comment]
can't tell you the reason for "last_move_failed" yet but about "any_move_successful": Based on the comment in Game_player this was for fixing broken Ice physics in the game "Glimpse". Maybe you can try removing that handling and playing the game again maybe you fixed it in a better way by now.

And the other corner case is standing on a "on touch" handler which executes a skippable move command but that command fails, then the "on touch" handler doesn't fire again.

**Comment by fmatthew5876** [comment]
This `last_move_failed` stuff seems not neccessary. I setup an event with move towards player with an obstacle in the way. As soon as I move the player around the event immediately changes direction to step towards the player.

**Comment by fmatthew5876** [comment]
I've tested all of the cases from 1 to 14 in #1567. This PR matches RPG_RT with some exceptions

* `move_type == random` has some wierd behavior that needs to be investigated further
* There are some timing issues with the interpreter, such as player move routes being skipped for the very first frame, resulting in some off by 1 frame mismatches from the test cases. These are interpreter timing issues and not move route logic issues, so I will consider them separately.

**Comment by fmatthew5876** [comment]
New changes, and now this PR passes test cases 15 and 16 from #1567.

Only caveat is again more instances of movement not being processed in the first frame.

**Comment by fmatthew5876** [comment]
Fixed #1429

**Comment by fmatthew5876** [comment]
Now passes Player #1567 Test cases 17 and 19

**Comment by fmatthew5876** [comment]
This now passes #1567 Test cases 18

**Comment by fmatthew5876** [comment]
This now passes test cases 22 and 23 (SetEventLocation and SetVehicleLocation). The jumping bug in RPG_RT is fixed in Player.

**Comment by fmatthew5876** [comment]
I've redone test cases 1 - 8. The remaining issues are:

- [ ] 8.1 - `stop_count` is 0 in Player. (autostart should be delayed by 1 frame)
- [ ] 8.2 - `stop_count` stops incrementing at 2 instead of 3 (same issue as above)
- [ ] 8.4 - `stop_count` freezes at 2 (autostart event should frame delays between each invocation)
- [ ] 8.5 - `stop_count` freezes at 0 (same issue as above)

**Comment by fmatthew5876** [comment]
I've gone through all of the test cases of #1567 again and marked the ones with differences in the previous comment.

All of the remaining issues are not really move route bugs but timing issues with the interpreter. They will be addressed in later PRs.

So this is ready for review and merge after 0.6.

**Comment by fmatthew5876** [comment]
Rebased to master

**Comment by Ghabry** [comment]
Can you sum up what you changed in bea23502701d0b019ff2b18b851c5675dcd89ee0 
That's really complex too review.

**Comment by fmatthew5876** [comment]
> Can you sum up what you changed in [bea2350](https://github.com/EasyRPG/Player/commit/bea23502701d0b019ff2b18b851c5675dcd89ee0)
> That's really complex too review.

Can I say "Make the test cases pass"? Really there was no way to break it down in to nice digestable chunks. I just kept fixing logic until it was matching RPG_RT. I apologize for that nasty commit.

**Comment by fmatthew5876** [comment]
For this one, instead of reviewing the diffs, it may be better to view the end results of `game_character`, `game_player`, `game_vehicle`, and `game_event` along with the test cases. There are so many changes here so that I don't think its possible to review them on a diff basis.

**Comment by Ghabry** [comment]
Removing ``IsBlockedByMoveRoute`` breaks moving even when you have a move route under certain circumstances.

Example, have a parallel event:
``
SetMoveRoute Player "Turn Right"
``

Result: Player should be able to walk normally but doesn't trigger Touch or Collision events anymore.

**Comment by Ghabry** [comment]
also breaks #937

**Comment by fmatthew5876** [comment]
> 
> 
> Removing `IsBlockedByMoveRoute` breaks moving even when you have a move route under certain circumstances.
> 
> Example, have a parallel event:
> `SetMoveRoute Player "Turn Right"`
> 
> Result: Player should be able to walk normally but doesn't trigger Touch or Collision events anymore.

I plan to fix those things more generally in #1628 later. But for now I can remove the `IsBlockedByMoveRoute` commit from here if thats blocking this one from merge,

**Comment by fmatthew5876** [comment]
I took out that commit and rebased to master

**Comment by Ghabry** [comment]
hmm, removing that commit didn't help, is still broken.

You also break #937 because you fixed a RPG_RT bug ;)

**Comment by fmatthew5876** [comment]
So there are 2 ways we can approach this:

1. Wait until I have 80+ commits from this, #1628, and others. Ensure absolutely no regressions and then review all of it and merge it all in one shot.
2. Reopen #937 (and any other regressions) to be fixed again properly in #1628. Then merge this PR soon.

I'm not in favor of (1) because it'll be a beast to review. Also getting some changes in piecemeal gives us time for further testing while the later interpreter work is pending,.

File: src/game_player.cpp [hunk 1]
```diff
@@ -640,6 +640,7 @@ void Game_Player::UnboardingFinished() {
 	Unboard();
 	if (InAirship()) {
 		SetDirection(RPG::EventPage::Direction_down);
+		SetSpriteDirection(RPG::EventPage::Direction_down);
```
Comment (Ghabry) [inline src/game_player.cpp]: > Player sprite should face down after exiting airship 

This could cause issues when the Player has a the facing locked. Did you test this?

File: src/game_character.cpp [hunk 2]
```diff
@@ -86,6 +86,8 @@ bool Game_Character::IsLandable(int x, int y) const
 
 	if (GetThrough()) return true;
 
+	if (IsFlying()) return true;
```
Comment (Ghabry) [inline src/game_character.cpp]: > Airship can jump and land anywhere 

Just a comment: It is confusing that "IsLandable" is not about Airship but Jump landing :D

File: src/game_player.cpp [hunk 3]
```diff
@@ -464,12 +464,14 @@ bool Game_Player::GetOnVehicle() {
 	data()->preboard_move_speed = GetMoveSpeed();
 	if (type != Game_Vehicle::Airship) {
 		data()->boarding = true;
-		if (!GetThrough()) {
-			SetThrough(true);
-			MoveForward();
-			SetThrough(false);
-		} else {
-			MoveForward();
+		if (!IsMoving() && !IsJumping()) {
```
Comment (Ghabry) [inline src/game_player.cpp]: > Fix ship disembark behavior 

Disembark onto water? How is this possible? Is that a bug, if yes could you add a comment somewhere.

File: src/game_character.cpp [hunk 4]
```diff
@@ -749,10 +745,6 @@ void Game_Character::BeginJump(int32_t& current_index, const RPG::MoveRoute& cur
 	SetStopCount(0);
 	SetMaxStopCountForStep();
 	move_failed = false;
-
-	if (IsContinuous()) {
-		SetAnimFrame(RPG::EventPage::Frame_middle);
-	}
```
Comment (Ghabry) [inline src/game_character.cpp]: Before a jump starts the animation is reset to the Middle frame.
Did you move this fix somewhere else?

File: src/game_character.cpp [hunk 5]
```diff
@@ -415,9 +410,6 @@ void Game_Character::UpdateMoveRoute(int32_t& current_index, const RPG::MoveRout
 				data()->route_through = false;
 				break;
 			case RPG::MoveCommand::Code::stop_animation:
-				if (IsContinuous()) {
-					SetAnimFrame(RPG::EventPage::Frame_middle);
-				}
```
Comment (Ghabry) [inline src/game_character.cpp]: > Animtype fixes 

Are you sure with this deletion? It was added because when "Stop Animation" is called the movement frame is  supposed to reset to middle.
I suppose the new fix is the commit after this one? (currently 09eff58 until a rebase)

File: src/game_player.cpp [hunk 6]
```diff
@@ -269,7 +269,8 @@ void Game_Player::Update(bool process_movement) {
 			}
 			SetMoveSpeed(vehicle->GetMoveSpeed());
 			vehicle->SetDirection(GetDirection());
-			vehicle->SetSpriteDirection(GetSpriteDirection());
+			vehicle->SetSpriteDirection(Left);
+			SetSpriteDirection(Left);
```
Comment (Ghabry) [inline src/game_player.cpp]: > Fix directions when finish boarding boat ship 

Same problem here with fixed graphics I suppose?

File: src/game_character.cpp [hunk 7]
```diff
@@ -224,21 +224,18 @@ void Game_Character::UpdateAnimation(bool was_moving) {
 	const auto stationary_limit = stationary_limits[step_idx];
 	const auto continuous_limit = continuous_limits[step_idx];
 
-	if (GetAnimCount() >= continuous_limit) {
-		IncAnimFrame();
-		return;
+	if (IsContinuous()
+			|| was_moving
+			|| data()->anim_frame == 0 || data()->anim_frame == 2
```
Comment (Ghabry) [inline src/game_character.cpp]: > Refactor animation count 

Where 0 and 2 left and right? --> enum

File: src/game_character.h [hunk 8]
```diff
@@ -1083,6 +1086,14 @@ inline void Game_Character::IncAnimCount() {
 
 inline void Game_Character::IncAnimFrame() {
 	data()->anim_frame = (data()->anim_frame + 1) % 4;
+	SetAnimCount(0);
+}
+
+inline void Game_Character::ResetAnimation() {
+	SetAnimCount(0);
+	if (GetAnimationType() != RPG::EventPage::AnimType_fixed_graphic) {
+		SetAnimFrame(1);
```
Comment (Ghabry) [inline src/game_character.h]: use the enum here RPG::EventPage::Frame_middle

File: src/game_event.cpp [hunk 9]
```diff
@@ -625,3 +626,7 @@ const RPG::SaveMapEvent& Game_Event::GetSaveData() {
 
 	return *data();
 }
+
+bool Game_Event::IsMoveRouteActive() const {
+	return true;
```
Comment (Ghabry) [inline src/game_event.cpp]: > Move route refactors

Why is this always true for events?

File: src/game_character.cpp [hunk 10]
```diff
@@ -149,33 +148,60 @@ int Game_Character::GetScreenZ(bool apply_shift) const {
...
 }
 
-void Game_Character::Update() {
-	if (GetStopCount() >= GetMaxStopCount()) {
-		if (IsMoveRouteOverwritten()) {
-			MoveTypeCustom();
-		} else {
-			// Only events
+void Game_Character::UpdateMovement() {
+	bool was_move_route_overriden = IsMoveRouteOverwritten();
```
Comment (Ghabry) [inline src/game_character.cpp]: > Move Route refactors
Is this unused? Can't find it in the diff

**Comment by Ghabry** [comment]
> So there are 2 ways we can approach this

I accept that the two issues can be fixed in a later PR if this becomes to chaotic one if them is a special interaction with the interpreter.
I added all fixed and broken issues to the first comment (10 fixes, 2 breakages, don't think we ever had so many issues fixed at once)

Also marked everything that I would like to have discussed, when this is handled I accept this PR. thx.

File: src/game_player.cpp (hunk 1 above)
Comment (fmatthew5876) [reply src/game_player.cpp]: It changes player direction even when facing locked flag is set. Player will be locked to down direction after landing airship.

File: src/game_character.cpp (hunk 2 above)
Comment (fmatthew5876) [reply src/game_character.cpp]: This mess is getting cleaned up in #1628

File: src/game_player.cpp (hunk 3 above)
Comment (fmatthew5876) [reply src/game_player.cpp]: Its in the test cases in #1429 

The code doesn't have anything specific to the "disembark into the water" bug.  It's just that it doesn't move again if you're already moving.

Do you still want some bug comment about that?

File: src/game_character.cpp (hunk 4 above)
Comment (fmatthew5876) [reply src/game_character.cpp]: This was moved to `UpdateAnimation()` under `if (IsJumping())`.

The logic here is wrong. It always resets the `anim_frame` (and `anim_count` too), regardless of your movement type.

File: src/game_character.cpp (hunk 5 above)
Comment (fmatthew5876) [reply src/game_character.cpp]: This was moved to `UpdateAnimation()`. Same comments as the jumping case.

File: src/game_player.cpp (hunk 6 above)
Comment (fmatthew5876) [reply src/game_player.cpp]: Flag is ignored, just like airship disembark.

File: src/game_character.h (hunk 8 above)
Comment (fmatthew5876) [reply src/game_character.h]: I can change these but we have 1 complication in that there are 2 frame middle values.

0 - left
1 - middle
2 - right
3 - middle

File: src/game_character.cpp (hunk 10 above)
Comment (fmatthew5876) [reply src/game_character.cpp]: Its unused, will remove

File: src/game_event.cpp (hunk 9 above)
Comment (fmatthew5876) [reply src/game_event.cpp]: It may be badly named, but I believe all the cases where its checked are always true for events but only true for player/vehicles with an active move route.

* Move route cancel - repeat logic - events can have custom move type so we need to check this
* `SetMaxStopCountForStep()` in `Game_Character::Move()` - This value is not set when the player moves via direction key. But is set for any event movement.
* `ForceMoveRoute()` - Need to clean up for events with custom move type.

This could use a refactor.

File: src/game_character.cpp (hunk 4 above)
Comment (fmatthew5876) [reply src/game_character.cpp]: Also I verified if you're movement type is `fixed_graphic`, jump doesn't reset the `anim_frame` or `anim_count`. That's handled `UpdateAnimation()`

File: src/game_player.cpp (hunk 1 above)
Comment (fmatthew5876) [reply src/game_player.cpp]: I added comments for this

**Comment by fmatthew5876** [comment]
I've addressed the review comments.

Very thorough review. I appreciate it!

File: src/game_character.h (hunk 8 above)
Comment (fmatthew5876) [reply src/game_character.h]: I added `Frame_middle2` in https://github.com/EasyRPG/liblcf/pull/316

The logic in `sprite_character.cpp:62` can be changed to use that enum value when its merged.

File: src/game_player.cpp (hunk 3 above)
Comment (Ghabry) [reply src/game_player.cpp]: no is fine, thanks for the explanation

File: src/game_character.h (hunk 8 above)
Comment (Ghabry) [reply src/game_character.h]: is in now :)

**Comment by fmatthew5876** [comment]
Added middle2 enum

File: src/game_character.cpp [hunk 11]
```diff
@@ -940,3 +940,19 @@ bool Game_Character::MakeWayDiagonal(int x, int y, int d) const {
 	return ((MakeWay(x, y, dy + 1) && MakeWay(x, y + dy, -dx + 2)) ||
 			(MakeWay(x, y, -dx + 2) && MakeWay(x + dx, y, dy + 1)));
 }
+
+void Game_Character::SetMaxStopCountForStep() {
+	const auto freq = GetMoveFrequency();
+	SetMaxStopCount(freq >= 8 ? 0 : 1 << (9 - GetMoveFrequency()));
```
Comment (carstene1ns) [inline src/game_character.cpp]: `GetMoveFrequency()` → `freq`?

Comment (fmatthew5876) [reply src/game_character.cpp]: Fixed and rebased to master. Thanks!
