### PR TITLE
De-magic-numbify some Z layer settings and BattleAnim-Picture-Render Order

### LINKED ISSUE #1195: Embric of Wulfhammer's Castle: Heavy flickering in intro scene
The carriage scene of this game's intro has heavy flickering, which was not an issue when I last tried quite a while ago. I bisected this and it seems the following commit causes the issue:

https://github.com/EasyRPG/Player/commit/ce4787d716690ac62a7a5aada3ad0e5f15e3d0ab

Problem is showcased in the following video: https://my.mixtape.moe/ywaqhy.mp4 
This was tested in Linux. To reproduce, simply start a new game and go through the intro until the scene appears.

### PR DESCRIPTION
**Pull request by Ghabry**
I hope I got all Z layer usages and didn't break something :/
The Z layers are now categorized in categories and the category marker are the upper 8 bit minus the sign bit. So 127 categories are possible (like a IPv4 Class A network ;)).

I didn't touch the Map Z layer stuff because I don't want to break the event order rendering... (but is in theory possible to figure out now because is all in PriorityMap)

The order has some limitations. See game_picture.cpp comments.

Fix #1195

### CODE REVIEW

File: src/window_message.cpp [hunk 1]
```diff
@@ -58,7 +58,7 @@ Window_Message::Window_Message(int ix, int iy, int iwidth, int iheight) :
 	}
 
 	visible = false;
-	SetZ(10000);
+		SetZ(PriorityWindow + 10);
```
Comment (fdelapena) [inline src/window_message.cpp]: accidental tab press

File: src/game_picture.cpp [hunk 2]
```diff
@@ -55,7 +55,15 @@ void Game_Picture::UpdateSprite() {
 
 	sprite->SetX((int)data.current_x);
 	sprite->SetY((int)data.current_y);
-	sprite->SetZ(1100 + data.ID);
+	if (Player::IsRPG2k3()) { // TODO: Including new RPG2k
+		// Battle Animations are above pictures
+		// ToDo: Include RPG Maker 2000 1.5 Value! and newer (How to detect?)
+		// ToDo: Exclude RPG Maker 2003 <1.05 (How to detect?)
```
Comment (carstene1ns) [inline src/game_picture.cpp]: Can this not be detected using kakurasan's changes?

File: src/sprite_battler.cpp [hunk 3]
```diff
@@ -259,7 +259,7 @@ void Sprite_Battler::CreateSprite() {
 
 	SetX(battler->GetBattleX());
 	SetY(battler->GetBattleY());
-	SetZ(battler->GetBattleY()); // Not a typo
+	SetZ(PriorityBattle + battler->GetBattleY()); // Not a typo
```
Comment (carstene1ns) [inline src/sprite_battler.cpp]: While we are at it, why not making this comment a bit more constructive?
Right as it is, this needs thinking over the purpose. Maybe something like this:
`// overlaps from top to bottom`

Comment (Ghabry) [inline src/sprite_battler.cpp]: The typo was about using GetBattleY instead of GetBattleZ (which doesn't exist). Yes these lines basicly mean that battler with a lower Y (so higher in the scene) appear behind battlers with higher Y.

File: src/game_picture.cpp (hunk 2 above)
Comment (Ghabry) [inline src/game_picture.cpp]: Yes the code is outdated and already handled by my other patch :)

File: src/sprite_battler.cpp (hunk 3 above)
Comment (carstene1ns) [inline src/sprite_battler.cpp]: Yeah, I understand what the comment means, but in my opinion should be reworded to make it better / constructive (and more clear for new contributors).

-
`//TODO: This is wrong` is a bad comment.
`//TODO: Needs foo and bar to work correctly` is a better comment.

Comment (Ghabry) [inline src/sprite_battler.cpp]: Yeah I agree with you

**Comment by Ghabry** [comment]
For this issue I would vote for a move directly behind 0.5.1 because (the not commited) Z-changes in above/below/same as hero events to be prepared for the next RPG2k3 version (pokes Cherry) will likely cause bugs. :)

File: src/window_message.cpp (hunk 1 above)
Comment (carstene1ns) [inline src/window_message.cpp]: Seems like you forgot to remove this 😁

**Comment by Ghabry** [comment]
Needs some ingame-testing first, though. Havn't checked the battle systems yet, was just happy that it compiled...

File: src/window_message.cpp [hunk 4]
```diff
@@ -58,7 +58,7 @@ Window_Message::Window_Message(int ix, int iy, int iwidth, int iheight) :
 	}
 
 	visible = false;
-	SetZ(10000);
+		SetZ(Priority_Window + 10);
```
Comment (carstene1ns) [inline src/window_message.cpp]: still accidental tab press here.

File: src/sprite_battler.cpp [hunk 5]
```diff
@@ -269,7 +269,8 @@ void Sprite_Battler::CreateSprite() {
 
 	SetX(battler->GetDisplayX());
 	SetY(battler->GetDisplayY());
-	SetZ(battler->GetBattleY()); // Not a typo
+	// Battlers at the bottom appear above battlers at the top
```
Comment (carstene1ns) [inline src/sprite_battler.cpp]: great comment!

**Comment by Ghabry** [comment]
Regression: Somehow the SetXYZ line in Sprite_Battler is duplicated and appears in Update() again and I missed that line. So the Z-value is incorrect and monster become (sometimes) invisible. I think simply removing that 3 lines is safe. Will submit a fix
