### PR TITLE
Various minor fixes

### LINKED ISSUE #2998: Minor stuff to fix
Stuff so small it is not worth a seperate issue but before I forget it:

- [x] Font API has inconsistent return value for GetSize (TTF)
- [x] Remove everything except ``code`` from shell file keyboard event handler
- [x] Viewport is not correctly centered when having an odd tilesize (?) (seems that using ``std::ceil`` instead of ``RoundTo`` works
- [x] opusfile not found anymore on windows
- [x] UBSan issues

### PR DESCRIPTION
**Pull request by Ghabry**
Fixes various minor stuff.

- [x] Opus works again on Windows
- [x] Emscripten touch still works
- [x] TTF Fonts still render correctly

Fix #2998

### CODE REVIEW

File: src/game_player.cpp [hunk 1]
```diff
@@ -755,11 +755,11 @@ void Game_Player::SetTotalEncounterRate(int rate) {
 }
 
 int Game_Player::GetDefaultPanX() {
-	return (Utils::RoundTo<int>(static_cast<float>(Player::screen_width) / TILE_SIZE / 2) - 1) * SCREEN_TILE_SIZE;
+	return static_cast<int>(std::ceil(static_cast<float>(Player::screen_width) / TILE_SIZE / 2) - 1) * SCREEN_TILE_SIZE;
```
Comment (Ghabry) [inline src/game_player.cpp:758]: oh this is already in. forgot to rebase :thinking:

**Comment by Ghabry** [comment]
Battle damage popup should now work again for all three cases: Built-in font, Bitmap font, True Type font. Please test.

**Review by fdelapena — APPROVED** [review]
