### PR TITLE
Fix emscripten (!)

### LINKED ISSUE #854: Investigate picojson crashes in emscripten
As mentioned in #842 picojson sometimes crashes in std::string._growby for no obvious reason.

I suggest trying to workaround this in picojson or to try different json libs until we randomly fix this crash... Strange stuff.

```
uncaught exception: abort() at jsStackTrace@https://easy-rpg.org/play/index-pr.js:1248:13
stackTrace@https://easy-rpg.org/play/index-pr.js:1265:22
abort@https://easy-rpg.org/play/index-pr.js:875474:44
_abort@https://easy-rpg.org/play/index-pr.js:8391:7
_free@https://easy-rpg.org/play/index-pr.js:400786:27
__ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE9__grow_byEjjjjjj [std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__grow_by(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int)]@https://easy-rpg.org/play/index-pr.js:802845:30
__ZN8picojson13_parse_stringINSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS1_19istreambuf_iteratorIcS4_EEEEbRT_RNS_5inputIT0_EE [bool picojson::_parse_string<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::istreambuf_iterator<char, std::__1::char_traits<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, picojson::input<std::__1::istreambuf_iterator<char, std::__1::char_traits<char> > >&)]@https://easy-rpg.org/play/index-pr.js:295865:7
__ZN8picojson6_parseINS_21default_parse_contextENSt3__119istreambuf_iteratorIcNS2_11char_traitsIcEEEEEEbRT_RNS_5inputIT0_EE [bool picojson::_parse<picojson::default_parse_context, std::__1::istreambuf_iterator<char, std::__1::char_traits<char> > >(picojson::default_parse_context&, picojson::input<std::__1::istreambuf_iterator<char, std::__1::char_traits<char> > >&)]@https://easy-rpg.org/play/index-pr.js:246537:10
__ZN8picojson6_parseINS_21default_parse_contextENSt3__119istreambuf_iteratorIcNS2_11char_traitsIcEEEEEEbRT_RNS_5inputIT0_EE [bool picojson::_parse<picojson::default_parse_context, std::__1::istreambuf_iterator<char, std::__1::char_traits<char> > >(picojson::default_parse_context&, picojson::input<std::__1::istreambuf_iterator<char, std::__1::char_traits<char> > >&)]@https://easy-rpg.org/play/index-pr.js:246964:12
__ZN10Scene_Logo12OnIndexReadyEP17FileRequestResult [Scene_Logo::OnIndexReady(FileRequestResult*)]@https://easy-rpg.org/play/index-pr.js:302316:11
__ZN5boost6detail8function26void_function_obj_invoker1INSt3__19binder1stINS3_10mem_fun1_tIv10Scene_LogoP17FileRequestResultEEEEvS8_E6invokeERNS1_15function_bufferES8_ [boost::detail::function::void_function_obj_invoker1<std::__1::binder1st<std::__1::mem_fun1_t<void, Scene_Logo, FileRequestResult*> >, void, FileRequestResult*>::invoke(boost::detail::function::function_buffer&, FileRequestResult*)]@https://easy-rpg.org/play/index-pr.js:823357:3
__ZN16FileRequestAsync13CallListenersEb [FileRequestAsync::CallListeners(bool)]@https://easy-rpg.org/play/index-pr.js:457901:5
__ZN16FileRequestAsync12DownloadDoneEb [FileRequestAsync::DownloadDone(bool)]@https://easy-rpg.org/play/index-pr.js:772514:2
__ZN12_GLOBAL__N_116download_successEjPvPKc [(anonymous namespace)::download_success(unsigned int, void*, char const*)]@https://easy-rpg.org/play/index-pr.js:848342:2
dynCall_viii@https://easy-rpg.org/play/index-pr.js:850505:2
Runtime.dynCall@https://easy-rpg.org/play/index-pr.js:515:14
http_onload@https://easy-rpg.org/play/index-pr.js:10178:1
```

### PR DESCRIPTION
**Pull request by Ghabry**
Change init strategy of rtp table from recursive std::initializer_list to seperate init_lists. This fixes a crash on emscripten and other platforms (3DS). Fix #854.

I read somewhere that this can segfault because the inner std::init_lists are a temporary. But I can't find the link anymore :(

### CODE REVIEW

**Comment by Ghabry** [comment]
Jenkins: test this please

**Comment by Ghabry** [comment]
Unfortunately this doesn't fix emscripten :(
But it fixes the 3DS so I will keep this open until I have integrated the 3DS code...

**Comment by Ghabry** [comment]
Somehow a crash that happened on 3DS (and probably PSP) also occured on emscripten but not on the Wii. This fixes it :)

File: src/rtp_table.h [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+ * along with EasyRPG Player. If not, see <http://www.gnu.org/licenses/>.
+ */
+
+#ifndef _RTP_TABLE_H_
+#define _RTP_TABLE_H_
+
+#include <map>
+#include <string>
+
+typedef std::map<std::string, std::map<std::string, std::string> > rtp_table_type;
```
Comment (fdelapena) [inline src/rtp_table.h]: Is the space between > and > still required in C++11?

Comment (Ghabry) [inline src/rtp_table.h]: no, will change it

**Comment by fdelapena** [comment]
> I read somewhere that this can segfault because the inner std::init_lists are a temporary. But I can't find the link anymore :(

http://en.cppreference.com/w/cpp/utility/initializer_list <-- as you pointed, the behavior changed since C++14 :+1:.
