### PR TITLE
MacOS Fixes

### LINKED ISSUE #3135: MIDI with soundfont - interrupting a MIDI with BGM (OFF) and playing another MIDI will play a note of the previous MIDI before playing the new one
#### Player platform:
Windows, 64 bits continuous build of the Player.

#### Describe the issue in detail and how to reproduce it:
While using a custom soundfont (the default setting on Windows does not work for this issue), interrupt a MIDI track with the command `Play BGM: (OFF)`, and then play another MIDI track (can be the same one). When the new MIDI track will play, some notes of the previous MIDI track will be heard while they should not.

You can test this with testgame: interact with the NPC on the left or right to play a MIDI, then the one at the center to stop it, and then the one on the left or right again to encounter the issue (make sure to have a custom soundfont to encounter the issue).
[MIDIissue.zip](https://github.com/EasyRPG/Player/files/13192033/MIDIissue.zip)

Reported by ajie on X, with the following footage as an example:
https://twitter.com/aj_108fn/status/1716463030903652845

### PR DESCRIPTION
**Pull request by tyrone-sudeium**
Fixes three issues:

- `5-beatles-lustig.mid` from Unterwegs in Duesterburg causes a crash in `MusicDeviceMIDIEvent` due to a bogus MIDI message. We're in some good company here, both VLC (at least on macOS) and Sekaiju also crash attempting to play it.
- I also noticed Unterwegs in Duesterburg in macOS has a _lot_ of stuck notes issues in macOS (i.e when changing BGM, some notes from the previous track will be permanently stuck on). I tracked it down to #3090 removing the `midimsg_all_sound_off` from reset, to be more accurate with Harmony. Harmony never supported macOS, and the macOS synthesizer being prone to stuck notes is why those messages were there in the first place. I'm open to other solutions to fix this, but without it, MIDI is pretty scuffed on Macs.
- The `-G Xcode` generator in cmake will completely fail to build (at least on Xcode 15), due to a fundamental disconnect between cmake and Xcode when you have multiple code files with the same filename (like `src/audio.cpp` vs `src/platform/sdl/audio.cpp`). Simplest workaround is to remove the duplication by renaming the two files that had duplicated names.

Fix #3135

### CODE REVIEW

**Review by Ghabry — CHANGES_REQUESTED** [review]
1. You inserted space instead of tab for the indent.
2. Can you add this ``NeedsSoftReset`` to Decoder Fluidsynth? Has a similiar issue and your fix is more universal.

**Review by fdelapena — APPROVED** [review]

File: src/audio_decoder_midi.cpp [hunk 1]
```diff
@@ -378,6 +402,10 @@ void AudioDecoderMidi::meta_event(int event, const void* data, std::size_t size)
 
 void AudioDecoderMidi::reset() {
 	// MIDI reset event
+	if (mididec->NeedsSoftReset()) {
+		// SoundOff every channel: necessary for synths like macOS which tend to get stuck
+		SendMessageToAllChannels(midimsg_all_sound_off(0));
```
Comment (Ghabry) [inline src/audio_decoder_midi.cpp:407]: sorry have to ask you for another small change:

Can you move this new code block between the GM reset and the pitch bend block? (I hope this doesn't break macOS?)

Tested this again in fluidsynth and the all sound off will not work properly when executed before the GM reset (same audio glitch remains).

```cpp
        // GM system on (resets most parameters)
        const unsigned char gm_reset[] = { 0xF0, 0x7E, 0x7F, 0x09, 0x01, 0xF7 };
        mididec->SendSysExMessage(gm_reset, sizeof(gm_reset));

        // MIDI reset event
        if (mididec->NeedsSoftReset()) {
                // SoundOff every channel: necessary for synths like macOS which tend to g>
                SendMessageToAllChannels(midimsg_all_sound_off(0));
        }

        // Set the Pitch bend range to 256
        for (int channel = 0; channel < 16; channel++) {
```

**Review by Ghabry — APPROVED** [review]
thanks, works now with fluidsynth :+1:
