### PR TITLE
Refactor and optimize Game_Picture + Wave fix - Bitmaps 2 of N

### LINKED ISSUE #1093: Rotation of a sprite that has a SubRect renders incorrectly
That's a problem when spritesheets (*cough* New RPG2k3 version *cough*) are involved. During a rotation the parts of the sprite that are not in the rect are visible:

bug

And the following lines in game_picture.cpp are wrong when a SubRect is involved (the pivot is placed incorrectly)
```cpp
sprite->SetOx((int)(sprite->GetBitmap()->GetWidth() / 2));
sprite->SetOy((int)(sprite->GetBitmap()->GetHeight() / 2));
```
Code to fix the pivot:
```cpp
sprite->SetOx((int)(sprite->GetWidth() / 2 + sprite->GetSrcRect().x));
sprite->SetOy((int)(sprite->GetHeight() / 2 + sprite->GetSrcRect().y));
```

### LINKED ISSUE #1883: Performance Regressions in script heavy games
Something has caused a performance regression in script heavy games.

- [x] もしもスマブラだったら (Wannabe Smash Bros.) http://viprpgsum15.webcrow.jp/sakuhin.html?71

- [ ] Frozen Triggers http://viprpg17kh.php.xdomain.jp/main/04_game.php?id=48

These games are currently unplayable in master with debug builds.

Looking at the graphs, these are performance bottlenecks in Frozen Triggers.

- [x] https://github.com/EasyRPG/Player/blob/0e05729f1c170e65800bfee487800c4e12e29683/src/cache.cpp#L128
    * Suggestion: Call `GetTicks()` once each frame and cache the value. Replace calls to `DisplayUI::GetTicks()` to the cached one
- [ ] https://github.com/EasyRPG/Player/blob/0e05729f1c170e65800bfee487800c4e12e29683/src/game_picture.cpp#L256
    * Suggestion: Cache / Reuse Picture Sprites
- [x] https://github.com/EasyRPG/Player/blob/0e05729f1c170e65800bfee487800c4e12e29683/src/game_picture.cpp#L253
    * Suggestion: Cache / Reuse Picture Sprites
- [ ] https://github.com/EasyRPG/Player/blob/aca489b85761d64d9d111589fe1848b16a18bc74/src/game_picture.cpp#L244
    * Calling `Bind()` allocates a `shared_ptr<int>`. In the case where the asset is already in the cache this is wasted. Provide an optimized code path which avoids allocating and throwing away these objects when the asset is already loaded in cache.

### PR DESCRIPTION
**Pull request by fmatthew5876**
Fix #1093
Fix #1883 

 * Remove sheet bitmap
 * Fix Effect's blit to properly handle src_rect for rotations in pixman

Tests with normal picture

For these tests I created several pictures with different sprite sheet frames of the actor1 charset. I also created a picture without a spritesheet.

For the 75% / 25% test, you have to hack player code because top/bottom trans are not supported in 2k3e.

Test Cases
- [x] No effects
- [x]  50% trans
- [x] 100% trans
- [x] 75% / 25% trans
- [x] 50% zoom
- [x] 50% zoom, 50% trans
- [x] 50% zoom, 100% trans
- [x] 50% zoom, 75% / 25% trans
- [x] 200% zoom
- [x] 200% zoom, 50% trans
- [x] 200% zoom, 100% trans
- [x] 200% zoom, 75% / 25% trans
- [x] Rotate
- [x] Rotate, 50% trans
- [x] Rotate, 100% trans
- [x] Rotate, 75% / 25% trans
- [x] Rotate, 50% zoom
- [x] Rotate, 50% zoom, 50% trans
- [x] Rotate, 50% zoom, 100% trans
- [x] Rotate, 50% zoom, 75% / 25% trans
- [x] Rotate, 200% zoom
- [x] Rotate, 200% zoom, 50% trans
- [x] Rotate, 200% zoom, 100% trans
- [x] Rotate, 200% zoom, 75% / 25% trans
- [x] Wave
- [x] Wave, 50% trans
- [x] Wave, 100% trans
- [x] Wave, 75% / 25% trans
- [x] Wave, 50% zoom
- [x] Wave, 50% zoom, 50% trans
- [x] Wave, 50% zoom, 100% trans
- [x] Wave, 50% zoom, 75% / 25% trans
- [x] Wave, 200% zoom
- [x] Wave, 200% zoom, 50% trans
- [x] Wave, 200% zoom, 100% trans
- [x] Wave, 200% zoom, 75% / 25% trans

### CODE REVIEW

**Comment by fmatthew5876** [comment]
This results in another significant speedup for Frozen Triggers!

#1986 
fzrotold

This PR
fzrotnew

I expect we'll see similar speed ups for newer sprite sheet heavy games.

**Comment by Ghabry** [comment]
When it works for rotation it fixes #1093. Can you confirm this?

**Comment by fmatthew5876** [comment]
#1093 was already fixed in master by using an extra bitmap. 

This fixes it properly and removes the need for that bitmap.

**Comment by fmatthew5876** [comment]
I tested this with all the cases added to the original post.

I also fixed a bug with wave blit and split opacity. This one could affect 2k3 1.0.8 games that use picture top and bottom transparency with wave effect.

**Comment by fmatthew5876** [comment]
When I was performance testing #1909 , I noticed for my test map with no pictures that `Game_Picture::Update()` was taking 3.8% of the runtime, despite there being no pictures. This was introduced with new RPG_RT behavior which always animate picture chunks, even if the picture is erased.

I added more optimizations to fix this scenario.

#1985 - You can see the time spent in `Game_Picture::SyncToFinish()`
picupdold

This + #1985 
picupdnew

**Comment by fmatthew5876** [comment]
This PR fixes #1883 .

With current master, debug builds of Frozen Triggers runs at 0 fps. With this PR I get 55 fps.

**Comment by fmatthew5876** [comment]
Rebased this and retested weather maps in my test game and pictures in Frozen Triggers.

File: src/game_screen.h [hunk 1]
```diff
@@ -247,4 +250,19 @@ inline bool Game_Screen::IsBattleAnimationWaiting() {
...
 
+inline Game_Picture& Game_Screen::GetPicture(int id) {
+	assert(id >= 0);
+
+	PreallocatePictureData(id);
+
+	return pictures[id - 1];
+}
+
+inline void Game_Screen::PreallocatePictureData(int id) {
```
Comment (Ghabry) [inline src/game_screen.h]: Why is there now DoPreallocatePicData and PreallocatePicData?

File: src/bitmap.h [hunk 2]
```diff
@@ -362,6 +350,37 @@ class Bitmap {
 	 */
 	void WaverBlit(int x, int y, double zoom_x, double zoom_y, Bitmap const& src, Rect const& src_rect, int depth, double phase, Opacity const& opacity);
 
+	/**
+	 * Blits source bitmap with transformation and opacity scaling.
+	 *
+	 * @param fwd forward (src->dst) transformation matrix.
```
Comment (Ghabry) [inline src/bitmap.h]: comment is outdated

File: src/game_screen.h (hunk 1 above)
Comment (fmatthew5876) [reply src/game_screen.h]: To inline the check for whether or not you should allocate. Since it's expected to almost never happen you can avoid the cost of a function call in the common case.

File: src/game_picture.h [hunk 3]
```diff
@@ -73,31 +73,35 @@ class Game_Picture {
 	void Move(const MoveParams& params);
 	void Erase(bool force_erase);
 
+	// FIXME: Use C++20 span
+	static void Update(std::vector<Game_Picture>& pictures);
+	// FIXME: Use C++20 span
+	static void UpdateSprite(std::vector<Game_Picture>& pictures);
```
Comment (Ghabry) [inline src/game_picture.h]: imo this adds an incentive to add an incentive to add this "FIXME: span" comment everywhere where std::vector is passed by reference and will keep it there for at least 5 years.

**Comment by fmatthew5876** [comment]
Fixed the comments

File: src/bitmap.h (hunk 2 above)
Comment (Ghabry) [reply src/bitmap.h]: Actually I meant the param list (fwd), not the text above, but good catch.

Comment (fmatthew5876) [reply src/bitmap.h]: Oops, fixed that one too now.

**Comment by Ghabry** [comment]
Jenkins: Test this please
