### PR TITLE
Fix use-after-free in Audio SDL Mixer

### LINKED ISSUE #2130: Crash when starting new game in windows
On windows debug build

Start the game at the title. As soon as I select New Game, I get this.

```
Exception thrown: read access violation.
**src32** was 0x256636C1620. occurred
```

```
Player.exe!SDL_MixAudioFormat_REAL(unsigned char * dst, const unsigned char * src, unsigned short format, unsigned int len, int volume) Line 155
	at C:\vcpkg\buildtrees\sdl2\src\ase-2.0.10-c1be3add38\src\audio\SDL_mixer.c(155)
Player.exe!mix_channels(void * udata, unsigned char * stream, int len) Line 318
	at C:\vcpkg\buildtrees\sdl2-mixer\src\2.0.4-a895b09396\mixer.c(318)
Player.exe!SDL_RunAudio(void * devicep) Line 737
	at C:\vcpkg\buildtrees\sdl2\src\ase-2.0.10-c1be3add38\src\audio\SDL_audio.c(737)
Player.exe!SDL_RunThread(void * data) Line 283
	at C:\vcpkg\buildtrees\sdl2\src\ase-2.0.10-c1be3add38\src\thread\SDL_thread.c(283)
[Inline Frame] Player.exe!RunThread(void *) Line 90
	at C:\vcpkg\buildtrees\sdl2\src\ase-2.0.10-c1be3add38\src\thread\windows\SDL_systhread.c(90)
Player.exe!RunThreadViaBeginThreadEx(void * data) Line 105
	at C:\vcpkg\buildtrees\sdl2\src\ase-2.0.10-c1be3add38\src\thread\windows\SDL_systhread.c(105)
Player.exe!thread_start<unsigned int (__cdecl*)(void *),1>(void * const parameter) Line 97
	at minkernel\crts\ucrt\src\appcrt\startup\thread.cpp(97)
[External Code]
```

It looks like a threading issue, where one thread is destroying data that the other thread references.

My suspicion (unconfirmed) is maybe it's a regression from this PR: https://github.com/EasyRPG/Player/pull/2119

Logfile:
```
Debug: EasyRPG Player 0.6.1 started
Debug: ============================
Debug: Clock: StdHigRes steady=1 period=ns (1 / 1000000000)
Debug: Seeded the RNG with 1586439675.
Debug: CLI: --window --test-play --project-path C:\Users\matt\Documents\RPG Maker 2003\DynGame --show-fps
Debug: SDL2: RendererInfo hw=1 sw=0 vsync=1
Debug: SDL2: Detected format (0) SDL_PIXELFORMAT_ARGB8888 : rank=(2)
Debug: SDL2: Selected Pixel Format SDL_PIXELFORMAT_ARGB8888
Debug: Opened audio at 44100 Hz (stereo), format: S16LSB
Debug: Cannot find: Title/title1
Debug: Detected encoding: UTF-8. Files not found. Trying next.
Debug: Cannot find: Title/title1
Debug: Detected encoding: ibm-5346_P100-1998. Files not found. Trying next.
Debug: Cannot find: Title/title1
Debug: Detected encoding: ibm-5348_P100-1997. Files not found. Trying next.
Debug: Cannot find: Title/τæ⌐τæ¼µö▒
Debug: Detected encoding: UTF-16BE. Files not found. Trying next.
Debug: Cannot find: Title/µÑ┤µ▒┤πàÑ
Debug: Detected encoding: UTF-16LE. Files not found. Trying next.
Debug: Cannot find: Title/title1
Debug: Detected encoding: ibm-943_P15A-2003. Files not found. Trying next.
Debug: Cannot find: Title/title1
Debug: Detected encoding: windows-936-2000. Files not found. Trying next.
Debug: Cannot find: Title/title1
Debug: Detected encoding: EUC-JP. Files not found. Trying next.
Debug: Cannot find: Title/title1
Debug: Detected encoding: windows-949-2000. Files not found. Trying next.
Debug: Cannot find: Title/title1
Debug: Detected encoding: Big5. Files not found. Trying next.
Debug: Cannot find: Title/title1
Debug: Detected encoding: ISO-8859-9. Files not found. Trying next.
liblcf:  ucnv_open() error for source encoding "IBM424_rtl": U_FILE_ACCESS_ERROR
Debug: Bad encoding: IBM424_rtl. Trying next.
Debug: Detected encoding: UTF-8
Debug: Using . as Game and Save directory
Debug: Loading game Untitled
Debug: Using RPG2k3 Interpreter
Debug: RPG2k >= v1.50 / RPG2k3 >= v1.05 detected
Debug: Engine configured as: 2k=0 2k3=1 MajorUpdated=1 Eng=0
Debug: Adding C:\Program Files (x86)\rpg2003\RTP to RTP path
Debug: RTP is "RPG Advocate English Translation" (675/675)
Debug: Adding C:\Program Files (x86)\Steam\steamapps\common\RPG Maker 2003\RTP to RTP path
Debug: RTP is "Official English" (675/675)
Debug: Cannot find: ./ExFont
Debug: Loading ExFont from .\RPG_RT.exe
Debug: EXEReader: EXFONT resource found (DE de2a0; e1718; len 2168)
Debug: Game uses RTP "RPG Advocate English Translation"
Debug: Actor 1: Removing item 44 from equipment slot 2 (Not equippable by this actor)
Debug: Actor 1: Removing item 67 from equipment slot 4 (Not equippable by this actor)
Debug: libpng: iCCP: known incorrect sRGB profile
Debug: libpng: cHRM: inconsistent chromaticities
Debug: WildMidi Failed: WildMidi: Could not find configuration file.
Debug: Starting new game
```

### PR DESCRIPTION
**Pull request by Ghabry**
The SE playback buffer was copied and not moved. The buffer used by SDL2 was invalid after returning from the function.

Not detected by ASAN because it happened in SDL :(

Fix #2130

### CODE REVIEW

**Comment by Ghabry** [comment]
Tested x86 and x64 Windows CI build: Works

File: src/audio_sdl_mixer.cpp [hunk 1]
```diff
@@ -625,7 +625,7 @@ void SdlMixerAudio::SE_Play(std::string const& file, int volume, int pitch) {
 		Output::Warning("Couldn't play %s SE. %s", FileFinder::GetPathInsideGamePath(file).c_str(), Mix_GetError());
 		return;
 	}
-	sounds[channel] = snd_data;
+	sounds[channel] = std::move(snd_data);
```
Comment (fmatthew5876) [inline src/audio_sdl_mixer.cpp:628]: Is it ever safe to copy this object?

If not we should `delete` the copy operations and `default` the move ones.

Comment (Ghabry) [reply src/audio_sdl_mixer.cpp:628]: That struct is specific to SDLMixer Audio. Will change it based on your suggestion.

**Comment by Ghabry** [comment]
Is the Default/Delete declaration correct this way? Never did this before.

File: src/audio_sdl_mixer.h [hunk 2]
```diff
@@ -73,6 +73,10 @@ class SdlMixerAudio : public AudioInterface {
 	bool played_once = false;
 
 	struct sound_data {
+		sound_data() = default;
+		sound_data(const sound_data&) = delete;
+		sound_data& operator=(sound_data&&) = default;
```
Comment (fmatthew5876) [inline src/audio_sdl_mixer.h:78]: Those are correct, but you also need to delete copy assignment and default move construction
