### PR TITLE
Window_ShopParty: render custom charset image sizes correctly

### LINKED ISSUE #1315: Shop loads CharSet images as if they would be prefixed with $ (dynamic size)
#### Name of the game: Final Tear 3
https://rpgmaker.net/games/3983/

#### Attach files (as a .zip archive or link them)

[Final Tear 3.zip](https://github.com/EasyRPG/Player/files/1536844/Final.Tear.3.zip)

Is either Save12 or 13. The correct one is the one in the fields.

#### Describe the issue in detail and how to reproduce it:

Walk down until you reach a city, go to the left and enter the shop.
When you want to buy something the character preview is wrong.
This is caused by the window buy code which assumes that the CharSet width is correct but the used file only contains one char. Imo the best way to solve this would be to configure custom Game_Characters and to simply render them into that field. Avoids code duplication.

### PR DESCRIPTION
**Pull request by fmatthew5876**
Fixes #1315.

### CODE REVIEW

File: src/sprite_character.cpp [hunk 1]
```diff
@@ -120,26 +120,32 @@ void Sprite_Character::OnTileSpriteReady(FileRequestResult*) {
...
 	// Allow large 4x2 spriteset of 3x4 sprites
 	// when the character name starts with a $ sign.
 	// This is not exactly the VX Ace way because
 	// VX Ace uses a single 1x1 spriteset of 3x4 sprites.
-	if (character_name.size() && character_name.at(0) == '$') {
-		chara_width = GetBitmap()->GetWidth() / 4 / 3 * (TILE_SIZE / 16);
-		chara_height = GetBitmap()->GetHeight() / 2 / 4 * (TILE_SIZE / 16);
+	if (!name.empty() && name.front() == '$') {
+		rect.width = bitmap_rect.width * (TILE_SIZE / 16) / 4;
+		rect.height = bitmap_rect.width * (TILE_SIZE / 16) / 2;
```
Comment (Ghabry) [inline src/sprite_character.cpp]: that should be .height

Comment (fmatthew5876) [reply src/sprite_character.cpp]: Nice catch, fixed!

**Comment by Ghabry** [comment]
but needs a rebase ;)
