### PR TITLE
Redirect Teleport and Escape skills that target areas to the owning map

### LINKED ISSUE #1253: Teleport and Escape skills don't handle Areas correctly
Please fill in the following fields before submitting an issue:
#### Name of the game:
DQ2　悪霊の勇者・製品版ver1.50  (and DQ but DQ2 has more such problems)

#### Attach files (as a .zip archive or link them)
Download: http://www1.axfc.net/uploader/so/1768371 (NFSW. full of hentai ads!)

Savegame: 
[Save01.zip](https://github.com/EasyRPG/Player/files/1246942/Save01.zip)

#### Describe the issue in detail and how to reproduce it:
Load the save, go to the item list and use the キメラ item. Select the only option and you get an error that map 35 is missing.

The map is indeed missing. It is an Area of map 1.

Looks like the Skills "Teleport" (teleports added through event "Add Teleport Place") and "Escape" (added through event "Add Escape Place") detect when the target is an area and change the target to the owner of the area.
The normal "Teleport" event command doesn't do this.

### PR DESCRIPTION
**Pull request by Ghabry**
The only games affected by this are the two japanese Dragon Quest fangames DQ列伝 and DQ2悪霊の勇者・製品版

Fix #1253

The two new functions in Game_Map could be used in some other places, too but I'm too afraid to break something...

### CODE REVIEW

File: src/game_player.cpp [hunk 1]
```diff
@@ -223,7 +223,14 @@ void Game_Player::ReserveTeleport(int map_id, int x, int y, int direction) {
 }
 
 void Game_Player::ReserveTeleport(const RPG::SaveTarget& target) {
-	ReserveTeleport(target.map_id, target.map_x, target.map_y, Down);
+	int map_id = target.map_id;
+
+	if (Game_Map::GetMapType(target.map_id) == 2) {
```
Comment (carstene1ns) [inline src/game_player.cpp]: We really need some enums/constants for such things.

Comment (Ghabry) [inline src/game_player.cpp]: I agree on this, but the build will fail now ;)

**Comment by carstene1ns** [comment]
jenkins: test this please
