### PR TITLE
KeyInputProc: Use correct behaviour depending on engine version

### LINKED ISSUE #2140: Saint Seiya Densetsu: Key Input not working in the "Improve" menu
#### Name of the game:
Saint Seiya Densetsu

https://www.facebook.com/ssdensetsu

https://drive.google.com/file/d/1dfmpUiosqSALQm38dM7VWzkO8wa4XDK2/view

#### Attach files (as a .zip archive or link them)

[Save15.zip](https://github.com/EasyRPG/Player/files/4463698/Save15.zip)

#### Describe the issue in detail and how to reproduce it:

"Improve setting, in this NPC, don't work d-pad to select character, in PC this works well."

Reported via E-Mail

### PR DESCRIPTION
**Pull request by Ghabry**
Not fully tested it yet but that should be it >.>

#2127 already implemented 2k Value! properly (by ignoring the 2k3 code path) but the key input was still broken for games created with RPG Maker 2003 < 1.05

Fix #2140

Here some testing. 2k3 has the same behaviour for all versions. 2k gained new stuff with "Value!".

The D means that the "Direction flag" (Arg 2) is 1.

|  Bytes | 2kDon | 2kE              |                           2k3 |                 Param  |
|--------|-------|------------------|-------------------------------|------------------------|
|   5D   |  Dir  | Dir              | Dir                           |   42 1 1 1 0    |
|   5    |       |                  |                               |       |
|   6D   |  Dir  | Shift            | Dir,Num                       |    42 1 1 1 0 1   |
|   6    |       | Shift            | Num                           |       |
|   7D   |  Dir  | Shift,Down       | Dir,Num                       |   42 1 1 1 0 1 1 |
|   7    |       | Shift,Down       | Num                           |                           |
|   8D   |  Dir  | Shift,Down       | Dir,Num,Ops                   |   42 1 1 1 0 1 1 0    |
|   8    |       | Shift,Down       | Num,Ops                       |       |
|   9D   |  Dir  | Shift,Down       | Dir,Num,Ops                   |   42 1 1 1 0 1 1 0 0    |
|   9    |       | Shift,Down       | Num,Ops                       |       |
|   10D  |  Dir  | Down,Up,Shift    | Down,Up,Shift                 |   42 1 1 1 0 1 1 0 0 1    |
|   10   |       | Down,Up,Shift    | Down,Up,Shift                 |            |
|   11D  |  Dir  | Down,Up,Shift    | Down,Shift,Num,Ops            |   42 1 1 1 0 1 1 0 0 1 1    |
|   11   |       | Down,Up,Shift    | Down,Shift,Num,Ops            |       |
|   12D  |  Dir  | Down,Up,Shift    | Left,Down,Shift,Num,Ops       |  42 1 1 1 0 1 1 0 0 1 1 1     |
|   12   |       | Down,Up,Shift    | Left,Down,Shift,Num,Ops       |       |
|   13D  |  Dir  | Down,Up,Shift    | Left,Down,Right,Shift,Num,Ops |   42 1 1 1 0 1 1 0 0 1 1 1 1    |

### CODE REVIEW

**Comment by Ghabry** [comment]
Here the test case.
Already bundles RPG2k (RPG_RT2k.exe), RPG2kValue (RPG_RT2kE.exe), RPG2k3 1.03 and RPG_RT2k3E (RPG_RT.exe)

The test is not very graphical. See in the editor: The 2 top rows are filled. The message indicates the length of the byte sequence. Top row is with dir flag. 2nd row without. "Confirm" ends the KeyInput, otherwise it echoes the input and repeats.

[KeyInputProc.zip](https://github.com/EasyRPG/Player/files/4465658/KeyInputProc.zip)

**Comment by Ghabry** [comment]
Added Engine checks to the KeyInputProc code and tested all our combinations (forced via --engine and based on RPG_RT.exe file in the directory). This is ready.

The RPG2k vs VALUE! code is already "battle-tested" a lot, so there shouldn't be lots of misdetections here.

For RPG2k3 we always assume "Newer" (1.05) when the file is missing and there are not many <1.05 games in the wild (are there any?), so the risk of misdetection is low.

Even a misdetection in favor of "newer engine" is usually not critical except for the edge case that the command is longer and hits one of the corner cases.

**Comment by Ghabry** [comment]
Many pushes later. Readded a comment that got lost and some typos >.>

File: src/game_interpreter.cpp [hunk 1]
```diff
@@ -2685,33 +2685,55 @@ bool Game_Interpreter::CommandKeyInputProc(RPG::EventCommand const& com) { // co
...
+				// For Rpg2k3 >=1.05
+				_keyinput.keys[Keys::eShift] = com.parameters[9] != 0;
+				_keyinput.keys[Keys::eDown] = com.parameters[10] != 0;
+				_keyinput.keys[Keys::eLeft] = param_size > 11 ? com.parameters[11] != 0 : false;
+				_keyinput.keys[Keys::eRight] = param_size > 12 ? com.parameters[12] != 0 : false;
+				_keyinput.keys[Keys::eUp] = param_size > 13 ? com.parameters[13] != 0 : false;
+			}
+		} else {
+			// Since RPG2k3 1.05
+			// Compatibility with RPG2k >=1.50
```
Comment (fmatthew5876) [inline src/game_interpreter.cpp:2730]: This and the RPG2k comment above in the 2k3 block are confusing. Since you (rightly) separated the 2k and 2k3 into separate blocks. Shouldn't we remove the 2k comments?

I would prefer to read it as "here are the 2k cases and over there are the 2k3 cases"

Comment (Ghabry) [reply src/game_interpreter.cpp:2730]: Removed some of the comments and reworded this one a bit. Because this looks very strange when looking at it (special case for param length 10?) I want to make it clear that this is for 2k games imported into 2k3

**Comment by Ghabry** [comment]
For reference the 2k3 >= 1.05 KeyInputProc:

The only thing we don't do this is altering the "all_direction" flag: (interesting for savegame compat?)

- Set to 0 when all_dir to 0 when command does not support all_dir
- Set to 1 when Up/Down/Left/Right are set

```c
int __usercall cmd_KeyInputProc@<eax>(struct_v3 *a1@<eax>, RPG_EventScriptData *a2@<ecx>)
{
  RPG_EventScriptData *v2; // esi
  struct_v3 *v3; // ebx
  int cmd_len; // eax
  int v5; // ecx
  RPG_Input *v6; // eax
  int result; // eax
  int v8; // ecx
  RPG_System *v9; // eax
  int v10; // eax

  v2 = a2;
  v3 = a1;
  a1->var_id = getEventParameter(a2, 0);
  v3->all_dir = getEventParameter(v2, 2);
  v3->decision = getEventParameter(v2, 3);
  v3->cancel = getEventParameter(v2, 4);
  v3->numbers = 0;
  v3->operators = 0;
  v3->time_variable = 0;
  v3->timed = 0;
  v3->shift = 0;
  v3->down = 0;
  v3->left = 0;
  v3->right = 0;
  v3->up = 0;
  cmd_len = v2->commandLen;
  // IsRPG2k3 <1.05 or RPG2k event cmd
  if ( cmd_len <= 10 )
  {
    if ( cmd_len <= 9 )
    {
      if ( cmd_len > 5 )
      {
        // Is a RPG2k3 <1.05 cmd
        v3->numbers = getEventParameter(v2, 5);
        v3->operators = getEventParameter(v2, 6);
        v3->time_variable = getEventParameter(v2, 7);
        v3->timed = getEventParameter(v2, 8);
      }
    }
    else
    {
      // Is a RPG2k command
      v3->all_dir = 0;
      v3->shift = getEventParameter(v2, 5);
      v3->down = getEventParameter(v2, 6);
      v3->left = getEventParameter(v2, 7);
      v3->right = getEventParameter(v2, 8);
      v3->up = getEventParameter(v2, 9);
    }
  }
  else
  {
    // Is a RPG2k3 >=1.05 cmd
    v3->numbers = getEventParameter(v2, 5);
    v3->operators = getEventParameter(v2, 6);
    v3->time_variable = getEventParameter(v2, 7);
    v3->timed = getEventParameter(v2, 8);
    v3->all_dir = 0;
    v3->shift = getEventParameter(v2, 9);
    v3->down = getEventParameter(v2, 10);
    v3->left = getEventParameter(v2, 11);
    v3->right = getEventParameter(v2, 12);
    v3->up = getEventParameter(v2, 13);
  }
  if ( v2->commandLen > 5 && v3->down && v3->left && v3->right && v3->up )
  {
    v3->down = 0;
    v3->left = 0;
    v3->right = 0;
    v3->up = 0;
    v3->all_dir = 1;
  }
  if ( v3->timed )
    v3->timer_related = 0;
  if ( (unsigned __int8)getEventParameter(v2, 1) )
  {
    v3->wait_for_input = 1;
    v6 = *RPG::input;
    result = sub_46D030();
  }
  else
  {
    v8 = sub_4AC2DC(v5, 0);
    v9 = *RPG::system;
    sub_48B3B0(v8, v3->var_id);
    v10 = *(_DWORD *)(*off_4CDD74 + 24);
    result = sub_4AB8B4();
  }
  return result;
}
```

**Comment by fmatthew5876** [comment]
For 2k English version:

```
int __usercall CommandKeyInputProc@<eax>(int a1@<eax>, RPG_EventScriptLine *a2@<ecx>)
{
  RPG_EventScriptLine *v2; // esi
  int v3; // ebx
  int result; // eax
  int v5; // eax
  int v6; // eax

  v2 = a2;
  v3 = a1;
  *(a1 + 12) = GetEventScriptLineParameter(a2, 0);
  *(v3 + 16) = GetEventScriptLineParameter(v2, 2);
  *(v3 + 17) = GetEventScriptLineParameter(v2, 3);
  *(v3 + 18) = GetEventScriptLineParameter(v2, 4);
  if ( v2->parameters.size <= 5 )
  {
    *(v3 + 19) = 0;
    *(v3 + 20) = 0;
    *(v3 + 21) = 0;
    *(v3 + 22) = 0;
    *(v3 + 23) = 0;
  }
  else
  {
    *(v3 + 16) = 0;
    *(v3 + 19) = GetEventScriptLineParameter(v2, 5);
    *(v3 + 20) = GetEventScriptLineParameter(v2, 6);
    *(v3 + 21) = GetEventScriptLineParameter(v2, 7);
    *(v3 + 22) = GetEventScriptLineParameter(v2, 8);
    *(v3 + 23) = GetEventScriptLineParameter(v2, 9);
    if ( *(v3 + 20) && *(v3 + 21) && *(v3 + 22) && *(v3 + 23) )
    {
      *(v3 + 20) = 0;
      *(v3 + 21) = 0;
      *(v3 + 22) = 0;
      *(v3 + 23) = 0;
      *(v3 + 16) = 1;
    }
  }
  if ( GetEventScriptLineParameter(v2, 1) )
  {
    *(v3 + 11) = 1;
    result = sub_457C68(*RPG::input);
  }
  else
  {
    v5 = sub_48C53C(v3, 0);
    SetVariable(*RPG::system, *(v3 + 12), v5);
    v6 = *(*off_4A0C78[0] + 24);
    result = sub_493188();
  }
  return result;
}
```
